ExamApp.Mvc/Models/AuthunticationVM.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ExamApp.Mvc.Models
{
    public class AuthunticationVM
    {
        [Required]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

ExamApp.Mvc/Models/CreateExamVM.cs
namespace ExamApp.Mvc.Models
{
    public class CreateExamVM
    {
        public int Id { get; set; }
        public required string Text { get; set; }
        public string? Description { get; set; }
        public DateTime? Duration { get; set; }
        public required bool IsVisible { get; set; }
    }
}

ExamApp.Mvc/Models/ErrorViewModel.cs
namespace ExamApp.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamApp.Mvc/Models/ExamVM.cs
namespace ExamApp.Mvc.Models
{
    public class ExamVM
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string? Description { get; set; }
        public DateTime? Duration { get; set; }
        public bool IsVisible { get; set; }
    }
}

ExamApp.Mvc/Models/RegisterVM.cs
using System.ComponentModel.DataAnnotations;

namespace ExamApp.Mvc.Models
{
    public class RegisterVM
    {
        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

ExamApp.Mvc/Models/SubmitAnswersVM.cs
namespace ExamApp.Mvc.Models
{
    public class SubmitAnswersVM
    {
        public required int ExamId { get; set; }
        public double? Mark { get; set; }
        public List<AnswerVM>? Answers { get; set; } = new List<AnswerVM>();
    }

    public class AnswerVM
    {
        public required int QuestionId { get; set; }
        public required int OptionId { get; set; }
    }
}

ExamApp.Mvc/Models/TakeExamVM.cs
namespace ExamApp.Mvc.Models
{
    public class TakeExamVM
    {
        public int Id { get; set; }
        public ExamVM Exam { get; set; } = new ExamVM();
        public List<QuestionVM> Questions { get; set; } = new List<QuestionVM>();
        //public int TotalQuestions => Questions.Count;
    }

    public class QuestionVM
    {
        public int Id { get; set; }
        public string Text { get; set; } = string.Empty;
        public double? Grade { get; set; }
        public List<OptionVM> Options { get; set; } = new List<OptionVM>();
    }

    public class OptionVM
    {
        public int Id { get; set; }
        public string Text { get; set; } = string.Empty;
        public bool IsTrue { get; set; }
    }
}

ExamApp.Mvc/Controllers/ExamController.cs
using AutoMapper;
using ExamApp.Mvc.Contracts;
using ExamApp.Mvc.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

namespace ExamApp.Mvc.Controllers
{
    public class ExamController : Controller
    {
        private readonly IExamService _examSrv;
        public ExamController(IExamService examSrv)
        {
            _examSrv = examSrv;
        }

        
        public async Task<ActionResult> Index()
        {
            var response = await _examSrv.GetAll();



            return View(response);
        }



        // GET: ExamController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var response = await _examSrv.Get(id);

            return View(response);
        }


        // GET: ExamController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ExamController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateExamVM obj)
        {
            try
            {
                await _examSrv.Create(obj);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ExamController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var response = await _examSrv.Get(id);

            return View(response);
        }

        // POST: ExamController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, ExamVM obj)
        {
            try
            {
                await _examSrv.Update(obj);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //// GET: ExamController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        // POST: ExamController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                await _examSrv.Delete(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public async Task<ActionResult> TakeExam(int id)
        {
            var response = await _examSrv.GetWholeExam(id);

            return View(response);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SubmitExam(SubmitAnswersVM vm)
        {
            try
            {
                await _examSrv.SubmitExam(vm);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
    }
}

ExamApp.Mvc/Controllers/HomeController.cs
using ExamApp.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ExamApp.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExamApp.Mvc/Controllers/UserController.cs
using ExamApp.Mvc.Contracts;
using ExamApp.Mvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace ExamApp.Mvc.Controllers
{
    public class UserController : Controller
    {
        private readonly IAuthService _authService;

        public UserController(IAuthService authService)
        {
            _authService = authService;
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(AuthunticationVM obj)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    var isAuthenticated = await _authService.Authunticate(obj);
                    if (isAuthenticated)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                ModelState.AddModelError("", "Invalid data");
                return View(obj);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }


        public ActionResult Register()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Register(RegisterVM obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var isRegistered = await _authService.Register(obj);
                    if (isRegistered)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                ModelState.AddModelError("", "Invalid data");
                return View(obj);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Logout(RegisterVM obj)
        {
            await _authService.Logout();

            return RedirectToAction("Index", "Home");
        }
    }
}

ExamApp.Mvc/Views/Exam/Create.cshtml
@model ExamApp.Mvc.Models.CreateExamVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CreateExamVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVisible" /> @Html.DisplayNameFor(model => model.IsVisible)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamApp.Mvc/Views/Exam/Details.cshtml
@model ExamApp.Mvc.Models.ExamVM

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ExamVM</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsVisible)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsVisible)
        </dd>
    </dl>
</div>
<div>

    @Html.ActionLink("Edit", "Edit", new {  id = Model.Id  }) |
    @Html.ActionLink("Take exam", "TakeExam", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

ExamApp.Mvc/Views/Exam/Edit.cshtml
@model ExamApp.Mvc.Models.ExamVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ExamVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVisible" /> @Html.DisplayNameFor(model => model.IsVisible)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamApp.Mvc/Views/Exam/Index.cshtml
@model IEnumerable<ExamApp.Mvc.Models.ExamVM>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Text)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsVisible)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsVisible)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |

                <form asp-action="Delete" asp-route-id="@item.Id" method="post" style="display:inline;">
                    @Html.AntiForgeryToken()
                    <button type="submit" onclick="return confirm('Are you sure you want to delete this?');">Delete</button>
                </form>
            </td>
        </tr>
}
    </tbody>
</table>

ExamApp.Mvc/Views/Exam/TakeExam.cshtml
@model TakeExamVM

@{
    ViewData["Title"] = "TakeExam";
}

<form asp-action="SubmitExam" method="post">
    <div class="exam">
	    <input type="hidden" name="ExamId" value="@Model.Id"/>

	    <div class="exam-header">
		    <h1>Take Exam: @Model.Exam.Text</h1>
		    <p>@Model.Exam.Description</p>
		    <p>Duration: @Model.Exam.Duration</p>
	    </div>

	    <div class="exam-questions">
            @for (int i = 0; i < Model.Questions.Count; i++)
            {
                var question = Model.Questions[i];

			    <input type="hidden" name="Answers[@(i)].QuestionId" value="@question.Id"/>

                <div class="question">
                    <div class="question-text">@($"{i + 1}. {question.Text}")</div>

                    @foreach (var option in question.Options)
                    {
                        <div class="option">
                            <input type="radio" name="Answers[@(i)].OptionId" value="@(option.Id)"/>
                            @option.Text
                        </div>
                    }
                </div>
            }
	    </div>

	    <div class="exam-footer">
		    <button type="submit" class="btn btn-primary">Submit Exam</button>
	    </div>
	</div>
</form>

ExamApp.Mvc/Views/Exam/TakeExamPage.cshtml
@{
}
<div class="exam">

	<div class="exam-header">
		<h1>Take Exam: @Model.Text</h1>
		<p>@Model.Description</p>
		<p>Duration: @Model.Duration minutes</p>
	</div>

	<div class="exam-questions">
        @for (int i = 0; i < Model.Questions.Count; i++)
        {
            var question = Model.Questions[i];
            <div class="question">
                <div class="question-text">@($"{i + 1}. {question.Text}")</div>

                @foreach (var option in question.Options)
                {
                    <div class="option">
                        <input type="radio" name="q@i" />
                        @option.Text
                    </div>
                }
            </div>
        }
	</div>

	<div class="exam-footer">
		<button class="btn btn-primary">Submit Exam</button>
	</div>

</div>

ExamApp.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>



</div>

ExamApp.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamApp.Mvc</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExamApp.Mvc.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExamApp.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @* @if(User.Identity.IsAuthenticated) *@
                        @if(true)
                        {
                            <li>
                                <a class="nav-link text-dark" asp-controller="Exam" asp-action="Index">Exams</a>
                            </li>


                            <li>
                                <form class="form-inline" method="post" asp-action="Logout" asp-controller="User">
                                    <button type="submit" class="nav-link btn btn-link ">
                                        Logout
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Login">Login</a>
                            </li>

                            <li>
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Register">Register</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ExamApp.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

ExamApp.Mvc/Views/User/Login.cshtml
@model ExamApp.Mvc.Models.AuthunticationVM

@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

<h4>AuthunticationVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamApp.Mvc/Views/User/Register.cshtml
@model ExamApp.Mvc.Models.RegisterVM

@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>

<h4>RegisterVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}